"""agregue tabla categorias

Revision ID: 415250de0cf2
Revises: d4ce13e3112c
Create Date: 2023-03-19 21:34:22.485545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415250de0cf2'
down_revision = 'd4ce13e3112c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('imagen', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias')
    # ### end Alembic commands ###
